export const products = [
  {
    id: "1",
    name: "Classic White T-Shirt",
    price: 25000,
    description:
      "A timeless classic white t-shirt made from 100% organic cotton for everyday comfort.",
    category: "t-shirts",
    sizes: ["S", "M", "L", "XL"],
    colors: ["white", "black", "gray"],
    stock: 50,
    images: [
      "/placeholder.svg?height=600&width=400",
      "/placeholder.svg?height=600&width=400",
    ],
    isBestseller: true,
    rating: 4.5,
    reviews: [],
  },
  {
    id: "2",
    name: "Slim Fit Jeans",
    price: 45000,
    description:
      "Modern slim fit jeans with a comfortable stretch fabric that moves with you.",
    category: "pants",
    sizes: ["30", "32", "34", "36"],
    colors: ["blue", "black", "gray"],
    stock: 35,
    images: [
      "/placeholder.svg?height=600&width=400",
      "/placeholder.svg?height=600&width=400",
    ],
    isBestseller: true,
    rating: 4.2,
    reviews: [],
  },
  {
    id: "3",
    name: "Casual Hoodie",
    price: 35000,
    description:
      "Cozy and stylish hoodie perfect for casual outings or relaxing at home.",
    category: "hoodies",
    sizes: ["S", "M", "L", "XL"],
    colors: ["navy", "black", "maroon"],
    stock: 25,
    images: [
      "/placeholder.svg?height=600&width=400",
      "/placeholder.svg?height=600&width=400",
    ],
    isBestseller: false,
    rating: 4.7,
    reviews: [],
  },
  {
    id: "4",
    name: "Summer Dress",
    price: 38000,
    description:
      "Light and flowy summer dress with a beautiful floral pattern.",
    category: "dresses",
    sizes: ["S", "M", "L"],
    colors: ["floral", "blue", "pink"],
    stock: 20,
    images: [
      "/placeholder.svg?height=600&width=400",
      "/placeholder.svg?height=600&width=400",
    ],
    isBestseller: false,
    rating: 4.8,
    reviews: [],
  },
  {
    id: "5",
    name: "Leather Jacket",
    price: 120000,
    description:
      "Premium leather jacket with a modern cut and durable construction.",
    category: "jackets",
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "brown"],
    stock: 15,
    images: [
      "/placeholder.svg?height=600&width=400",
      "/placeholder.svg?height=600&width=400",
    ],
    isBestseller: true,
    rating: 4.9,
    reviews: [],
  },
  {
    id: "6",
    name: "Athletic Shorts",
    price: 22000,
    description:
      "Lightweight athletic shorts with moisture-wicking technology for your workouts.",
    category: "shorts",
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "gray", "blue"],
    stock: 40,
    images: [
      "/placeholder.svg?height=600&width=400",
      "/placeholder.svg?height=600&width=400",
    ],
    isBestseller: false,
    rating: 4.3,
    reviews: [],
  },
  {
    id: "7",
    name: "Sports Sneakers",
    price: 55000,
    description:
      "High-performance sports sneakers with breathable mesh and shock-absorbing soles.",
    category: "shoes",
    sizes: ["40", "41", "42", "43", "44"],
    colors: ["white", "black", "red"],
    stock: 30,
    images: [
      "/placeholder.svg?height=600&width=400",
      "/placeholder.svg?height=600&width=400",
    ],
    isBestseller: true,
    rating: 4.6,
    reviews: [],
  },
  {
    id: "8",
    name: "Denim Jacket",
    price: 65000,
    description:
      "Classic denim jacket with a vintage wash and durable stitching.",
    category: "jackets",
    sizes: ["S", "M", "L", "XL"],
    colors: ["blue", "black"],
    stock: 20,
    images: [
      "/placeholder.svg?height=600&width=400",
      "/placeholder.svg?height=600&width=400",
    ],
    isBestseller: true,
    rating: 4.5,
    reviews: [],
  },
  {
    id: "9",
    name: "Cargo Pants",
    price: 40000,
    description:
      "Comfortable and stylish cargo pants with multiple pockets and a relaxed fit.",
    category: "pants",
    sizes: ["30", "32", "34", "36"],
    colors: ["khaki", "black", "olive"],
    stock: 25,
    images: [
      "/placeholder.svg?height=600&width=400",
      "/placeholder.svg?height=600&width=400",
    ],
    isBestseller: false,
    rating: 4.4,
    reviews: [],
  },
  {
    id: "10",
    name: "Formal Dress Shirt",
    price: 48000,
    description:
      "Elegant formal dress shirt made from premium cotton for a polished look.",
    category: "shirts",
    sizes: ["S", "M", "L", "XL"],
    colors: ["white", "blue", "gray"],
    stock: 30,
    images: [
      "/placeholder.svg?height=600&width=400",
      "/placeholder.svg?height=600&width=400",
    ],
    isBestseller: false,
    rating: 4.7,
    reviews: [],
  },
  {
    id: "11",
    name: "Chino Shorts",
    price: 27000,
    description: "Smart casual chino shorts perfect for summer outings.",
    category: "shorts",
    sizes: ["S", "M", "L", "XL"],
    colors: ["beige", "navy", "black"],
    stock: 35,
    images: [
      "/placeholder.svg?height=600&width=400",
      "/placeholder.svg?height=600&width=400",
    ],
    isBestseller: true,
    rating: 4.6,
    reviews: [],
  },
  {
    id: "12",
    name: "Winter Coat",
    price: 150000,
    description:
      "Heavy-duty winter coat with thermal insulation for extreme cold weather.",
    category: "coats",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["black", "gray"],
    stock: 10,
    images: [
      "/placeholder.svg?height=600&width=400",
      "/placeholder.svg?height=600&width=400",
    ],
    isBestseller: true,
    rating: 4.9,
    reviews: [],
  },
  {
    id: "13",
    name: "Graphic T-Shirt",
    price: 28000,
    description: "Trendy graphic t-shirt with unique printed designs.",
    category: "t-shirts",
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "white", "red"],
    stock: 40,
    images: [
      "/placeholder.svg?height=600&width=400",
      "/placeholder.svg?height=600&width=400",
    ],
    isBestseller: false,
    rating: 4.5,
    reviews: [],
  },
  {
    id: "14",
    name: "Running Shoes",
    price: 60000,
    description: "Lightweight running shoes designed for comfort and speed.",
    category: "shoes",
    sizes: ["39", "40", "41", "42", "43"],
    colors: ["white", "black", "blue"],
    stock: 25,
    images: [
      "/placeholder.svg?height=600&width=400",
      "/placeholder.svg?height=600&width=400",
    ],
    isBestseller: true,
    rating: 4.8,
    reviews: [],
  },
  {
    id: "15",
    name: "Wool Sweater",
    price: 70000,
    description: "Soft and warm wool sweater, ideal for chilly days.",
    category: "sweaters",
    sizes: ["S", "M", "L", "XL"],
    colors: ["gray", "navy", "burgundy"],
    stock: 20,
    images: [
      "/placeholder.svg?height=600&width=400",
      "/placeholder.svg?height=600&width=400",
    ],
    isBestseller: false,
    rating: 4.7,
    reviews: [],
  },
];

export const categories = [
  { id: "all", name: "All Products" },
  { id: "t-shirts", name: "T-Shirts" },
  { id: "pants", name: "Pants" },
  { id: "hoodies", name: "Hoodies" },
  { id: "dresses", name: "Dresses" },
  { id: "jackets", name: "Jackets" },
  { id: "shorts", name: "Shorts" },
  { id: "shoes", name: "Shoes" },
  { id: "coats", name: "Coats" },
  { id: "sweaters", name: "Sweaters" },
  { id: "shirts", name: "Shirts" },
  { id: "accessories", name: "Accessories" },
];
